name: Build

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build for all platforms
        run: |
          curl -L -o ./bagop "https://github.com/pojntfx/bagop/releases/latest/download/bagop.linux-$(uname -m)"
          chmod +x ./bagop
          CGO_ENABLED=0 ./bagop -b IsMyPortOpen --exclude "(android/*|ios/*|js/*)" .
          echo VER=$(cat ./VERSION) >> $GITHUB_ENV

      - name: Create Release and Upload binaries
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          tag_name: ${{ env.VER }}
          files: |
            out/*
            VERSION
